### ISSUE TITLE
Backlash for XYZABC instead of for joints

### ISSUE THREAD

**Issue by maxschommer** [Koeng101/armos#1]
This might be a misunderstanding of the code, but I noticed in a schema:

```
backlashA REAL,
backlashB REAL,
backlashC REAL,
backlashX REAL,
backlashY REAL,
backlashZ REAL
```

If this is to model robot arm backlash, a better model might be scalars of radians associated with each joint instead. If this is not to model robot arm backlash, close this issue.

**Comment by Koeng101** [comment]
Why would scalars of radians associated with each joint be better?

**Comment by maxschommer** [comment]
Backlash is fundamentally a joint-induced thing. So each joint, when the stepper motor is frozen, allows some angular "backlash" of +- some amount. The backlash in XYZABC at the end effector is determined on pose, and is therefore a derived parameter.

**Comment by Koeng101** [comment]
Fixed.
